# Generated by Django 5.2.7 on 2025-10-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaborador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="colaborador.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="data_admissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
