"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from dotenv import load_dotenv # Usaremos python-dotenv para ler o arquivo .env

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# A chave secreta é lida da variável de ambiente DJANGO_SECRET_KEY
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("A variável de ambiente DJANGO_SECRET_KEY não foi definida.")


# SECURITY WARNING: don't run with debug turned on in production!
# O modo DEBUG é controlado pela variável de ambiente DEBUG (True ou False)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # --- Apps de Terceiros ---
    'rest_framework',       # Para a criação de APIs
    'drf_spectacular',      # Para a documentação (Swagger UI)
    'guardian',             # Para permissões por objeto (por unidade)
    'cpf_field',            # Para validação de CPF
    
    # --- Nossas Apps ---
    'usuarios',
    'agendamentos',
    'financeiro',
    'avaliacoes',
    # Adicione aqui outras apps que criar, como 'unidades', 'planos', etc.
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- Bloco de Banco de Dados Lendo do .env ---
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# --- Configurações de Idioma e Fuso Horário ---
LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- Configuração do Modelo de Usuário Customizado ---
# Aponta para o modelo de usuário que você criará no seu app 'usuarios'
AUTH_USER_MODEL = 'usuarios.Usuario'


# --- Configurações de Autenticação (incluindo Django Guardian) ---
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # Autenticação padrão do Django
    'guardian.backends.ObjectPermissionBackend', # Backend para permissões por objeto
)


# --- Configurações do Django REST Framework e Swagger ---
REST_FRAMEWORK = {
    # Define o gerador de esquema da API para o drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# --- Configuração de E-mail (para desenvolvimento) ---
# Imprime os e-mails no console em vez de enviá-los de verdade.
# Ótimo para testar o fluxo de "esqueci minha senha".
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'