# Generated by Django 5.2.7 on 2025-10-14 15:51

import cpf_field.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="alunos/")),
                ("dataNascimento", models.DateField(verbose_name="Data de Nascimento")),
                ("cpf", cpf_field.models.CPFField(max_length=14, unique=True)),
                (
                    "contato",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="BR"
                    ),
                ),
                ("profissao", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "db_table": "alunos",
            },
        ),
    ]
