# Generated by Django 5.2.7 on 2025-10-11 17:51

import alunos.models
import cpf_field.models
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="alunos/")),
                ("dataNascimento", models.DateField(verbose_name="Data de Nascimento")),
                ("cpf", cpf_field.models.CPFField(max_length=14)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "contato",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="BR"
                    ),
                ),
                ("profissao", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("email_verificado", models.BooleanField(default=False)),
                (
                    "token_verificado",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "token_usuario",
                    models.TextField(default=alunos.models.generate_token),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "db_table": "alunos",
            },
        ),
    ]
