# Generated by Django 5.2.7 on 2025-10-30 01:20

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studios", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="fotos_alunos/"),
                ),
                ("dataNascimento", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "contato",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="BR", verbose_name="Telefone de Contato"
                    ),
                ),
                ("profissao", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "unidades",
                    models.ManyToManyField(related_name="alunos", to="studios.studio"),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "db_table": "alunos",
            },
        ),
    ]
