# Generated by Django 5.2.7 on 2025-10-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('studios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='unidades',
            field=models.ManyToManyField(related_name='alunos', to='studios.studio'),
        ),
    ]
