# Generated by Django 5.2.7 on 2025-10-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_alunos/"),
        ),
    ]
