# Generated by Django 5.2.7 on 2025-10-18 05:33

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_aluno_unidades"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="cpf",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="contato",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BR", verbose_name="Telefone de Contato"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
    ]
