# Generated by Django 5.2.6 on 2025-09-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
