# Generated by Django 5.2.7 on 2025-11-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor_pago", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("CANCELADA", "Cancelada"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="ATIVA",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "db_table": "matriculas",
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pagamento", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_modificacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "db_table": "pagamentos",
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_parcela", models.IntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "parcelas",
            },
        ),
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("duracao_dias", models.IntegerField(default=30)),
                ("creditos_semanais", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_modificacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
                "db_table": "planos",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade_estoque", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produtos",
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "db_table": "vendas",
            },
        ),
        migrations.CreateModel(
            name="VendaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "venda_produtos",
            },
        ),
    ]
