# Generated by Django 5.2.8 on 2025-11-05 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matricula",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pagamento",
            options={},
        ),
        migrations.AlterModelOptions(
            name="plano",
            options={},
        ),
        migrations.AlterModelOptions(
            name="produto",
            options={},
        ),
        migrations.AlterModelOptions(
            name="venda",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="parcela",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vendaproduto",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="status",
        ),
        migrations.RemoveField(
            model_name="matricula",
            name="valor_pago",
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="pagamento",
            name="data_ultima_modificacao",
        ),
        migrations.RemoveField(
            model_name="plano",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="plano",
            name="data_ultima_modificacao",
        ),
        migrations.AddField(
            model_name="pagamento",
            name="comprovante_pagamento",
            field=models.FileField(
                blank=True, null=True, upload_to="comprovantes_pagamento/"
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="plano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financeiro.plano"
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="metodo_pagamento",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PAGO", "Pago"),
                    ("ATRASADO", "Atrasado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PAGO", "Pago"),
                    ("ATRASADO", "Atrasado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="plano",
            name="duracao_dias",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="plano",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade_estoque",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="venda",
            name="aluno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_venda",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vendaproduto",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financeiro.produto"
            ),
        ),
        migrations.AlterField(
            model_name="vendaproduto",
            name="quantidade",
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name="matricula",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pagamento",
            table=None,
        ),
        migrations.AlterModelTable(
            name="parcela",
            table=None,
        ),
        migrations.AlterModelTable(
            name="plano",
            table=None,
        ),
        migrations.AlterModelTable(
            name="produto",
            table=None,
        ),
        migrations.AlterModelTable(
            name="venda",
            table=None,
        ),
        migrations.AlterModelTable(
            name="vendaproduto",
            table=None,
        ),
    ]
