# Generated by Django 5.2.7 on 2025-11-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matriculas",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="matricula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="financeiro.matricula",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="pagamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas",
                to="financeiro.pagamento",
            ),
        ),
        migrations.AddField(
            model_name="matricula",
            name="plano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="financeiro.plano",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="aluno",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="pagamento",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="financeiro.venda",
            ),
        ),
        migrations.AddField(
            model_name="vendaproduto",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="financeiro.produto"
            ),
        ),
        migrations.AddField(
            model_name="vendaproduto",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financeiro.venda"
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="produtos",
            field=models.ManyToManyField(
                through="financeiro.VendaProduto", to="financeiro.produto"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parcela",
            unique_together={("pagamento", "numero_parcela")},
        ),
        migrations.AlterUniqueTogether(
            name="vendaproduto",
            unique_together={("venda", "produto")},
        ),
    ]
