# Generated by Django 5.2.7 on 2025-11-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_alter_matricula_options_alter_pagamento_options_and_more"),
        ("studios", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="quantidade_estoque",
        ),
        migrations.AddField(
            model_name="matricula",
            name="studio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="studios.studio",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="studio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="studios.studio",
            ),
        ),
        migrations.CreateModel(
            name="EstoqueStudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="financeiro.produto",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "unique_together": {("produto", "studio")},
            },
        ),
    ]
