# Generated by Django 5.2.7 on 2025-11-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financeiro",
            "0003_remove_produto_quantidade_estoque_matricula_studio_and_more",
        ),
        ("studios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="studio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="studios.studio",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="studio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="studios.studio",
            ),
        ),
    ]
