# Generated by Django 5.2.7 on 2025-11-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_alter_matricula_studio_alter_venda_studio"),
        ("studios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="studio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="studios.studio",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="studio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="studios.studio",
            ),
        ),
    ]
