# Generated by Django 5.2.8 on 2025-11-14 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_alter_matricula_studio_alter_venda_studio"),
        ("studios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoquestudio",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="financeiro.produto"
            ),
        ),
        migrations.AlterField(
            model_name="estoquestudio",
            name="quantidade",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="estoquestudio",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studios.studio"
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="studio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matriculas",
                to="studios.studio",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="studio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="studios.studio",
            ),
        ),
    ]
