# Generated by Django 5.2.8 on 2025-11-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_alter_estoquestudio_produto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
