# Generated by Django 5.2.7 on 2025-10-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EVOLUCAO", "Evolução"),
                            ("PLANEJAMENTO", "Planejamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "registros_clinicos",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                ("diagnostico", models.TextField(blank=True)),
                ("historico_medico", models.TextField(blank=True)),
                ("data_proxima_reavaliacao", models.DateField(blank=True, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_modificacao", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="alunos.aluno",
                    ),
                ),
            ],
            options={
                "db_table": "avaliacoes",
            },
        ),
    ]
