# Generated by Django 5.2.7 on 2025-10-13 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EVOLUCAO", "Evolução"),
                            ("PLANEJAMENTO", "Planejamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "registros_clinicos",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_avaliacao", models.DateField(verbose_name="Data de Avaliação")),
                (
                    "diagnostico_fisioterapeutico",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Diagnóstico Fisioterapeutico",
                    ),
                ),
                (
                    "historico_medico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Histórico Médico"
                    ),
                ),
                (
                    "patologias",
                    models.TextField(blank=True, null=True, verbose_name="Patologias"),
                ),
                (
                    "exames_complementares",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exames Complementares"
                    ),
                ),
                (
                    "medicamentos_em_uso",
                    models.TextField(
                        blank=True, null=True, verbose_name="Medicamentos em Uso"
                    ),
                ),
                (
                    "tratamentos_realizados",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tratamentos Anteriores"
                    ),
                ),
                ("objetivo_aluno", models.TextField(verbose_name="Objetivo do Aluno")),
                (
                    "foto_avaliacao_postural",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avaliacoes/",
                        verbose_name="Foto da Avaliação Postural",
                    ),
                ),
                (
                    "data_reavalicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data para Reavaliação"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_modificacao", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="alunos.aluno",
                    ),
                ),
            ],
            options={
                "db_table": "avaliacoes",
                "ordering": ["-data_avaliacao"],
            },
        ),
    ]
