# Generated by Django 5.2.7 on 2025-10-11 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0002_initial"),
        ("avaliacoes", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="instrutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avaliacoes_realizadas",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="registroclinico",
            name="aula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agendamentos.aula",
            ),
        ),
        migrations.AddField(
            model_name="registroclinico",
            name="avaliacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="avaliacoes.avaliacao",
            ),
        ),
        migrations.AddField(
            model_name="registroclinico",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="usuarios.colaborador"
            ),
        ),
    ]
