# Generated by Django 5.2.7 on 2025-11-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0001_initial"),
        ("studios", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="studio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes",
                to="studios.studio",
            ),
        ),
    ]
