# Generated by Django 5.2.7 on 2025-10-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="instrutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="avaliacoes_realizadas",
                to="usuarios.colaborador",
            ),
        ),
    ]
