# Generated by Django 5.2.7 on 2025-10-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0003_alter_avaliacao_instrutor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliacao",
            options={
                "ordering": ["-data_avaliacao"],
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
            },
        ),
        migrations.AlterModelOptions(
            name="registroclinico",
            options={
                "ordering": ["-data_registro"],
                "verbose_name": "Registro Clínico",
                "verbose_name_plural": "Registros Clínicos",
            },
        ),
        migrations.AlterField(
            model_name="registroclinico",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data do Registro"
            ),
        ),
        migrations.AlterField(
            model_name="registroclinico",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="registroclinico",
            name="tipo",
            field=models.CharField(
                choices=[("EVOLUCAO", "Evolução"), ("PLANEJAMENTO", "Planejamento")],
                max_length=20,
                verbose_name="Tipo de Registro",
            ),
        ),
    ]
