# Generated by Django 5.2.6 on 2025-09-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
