# Generated by Django 5.2.6 on 2025-09-26 17:56

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_aluno_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14),
        ),
    ]
