# Generated by Django 5.2.6 on 2025-09-26 18:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_aluno_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="contato",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BR"
            ),
        ),
    ]
