# Generated by Django 5.2.6 on 2025-09-26 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_aluno_contato"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="email_verificado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aluno",
            name="token_verificado",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
