# Generated by Django 5.2.7 on 2025-10-15 01:37

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="cpf",
        ),
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=cpf_field.models.CPFField(
                blank=True,
                help_text="CPF do usuário. Será usado como identificador único.",
                max_length=14,
                null=True,
                unique=True,
            ),
        ),
    ]
