# Generated by Django 5.2.6 on 2025-09-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(related_name="usuario_set", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="usuario_set", to="auth.permission"
            ),
        ),
    ]
