# Generated by Django 5.2.8 on 2025-11-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="registro_profissional",
            field=models.CharField(
                blank=True,
                help_text="Ex: CREFITO para fisioterapeutas, CREF para instrutores",
                max_length=50,
                null=True,
            ),
        ),
    ]
