# Generated by Django 5.2.7 on 2025-10-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_colaborador_cpf_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ADMIN_MASTER', 'Admin Master'), ('ADMINISTRADOR', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('INSTRUTOR', 'Instrutor')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='perfil',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='perfis',
            field=models.ManyToManyField(related_name='colaboradores', to='usuarios.perfil'),
        ),
    ]
