# Generated by Django 5.2.7 on 2025-10-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0002_initial"),
        ("usuarios", "0004_populate_perfis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="unidades",
        ),
        migrations.AddField(
            model_name="colaborador",
            name="unidades_old",
            field=models.ManyToManyField(
                related_name="colaboradores_old", to="studios.studio"
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="registro_profissional",
            field=models.CharField(
                blank=True,
                help_text="Ex: CREFITO para fisioterapeutas, CREF para instrutores",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(help_text="CEP no formato XXXXX-XXX", max_length=9),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="estado",
            field=models.CharField(help_text="Sigla do estado, ex: SP", max_length=2),
        ),
    ]
