# Generated by Django 5.2.7 on 2025-10-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0002_initial"),
        (
            "usuarios",
            "0005_remove_colaborador_unidades_colaborador_unidades_old_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="unidades",
            field=models.ManyToManyField(
                related_name="colaboradores",
                through="studios.ColaboradorStudio",
                to="studios.studio",
            ),
        ),
    ]
