# Generated by Django 5.2.6 on 2025-09-27 13:51

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_aluno_email_verificado_aluno_token_verificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="token_usuario",
            field=models.TextField(default=usuarios.models.generate_token),
        ),
    ]
