# Generated by Django 5.2.7 on 2025-10-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_colaborador_unidades"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="unidades_old",
        ),
    ]
