# Generated by Django 5.2.6 on 2025-10-13 04:00

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_aluno_token_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="email_verificado",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="token_verificado",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="cpf"),
        ),
    ]
