# Generated by Django 5.2.6 on 2025-09-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_aluno_token_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoInicial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_avaliacao", models.DateField(verbose_name="Data de Avaliação")),
                (
                    "diagnostico_fisioterapeutico",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Diagnóstico Fisioterapeutico",
                    ),
                ),
                (
                    "historico_medico",
                    models.TextField(
                        blank=True, null=True, verbose_name="Histórico Médico"
                    ),
                ),
                (
                    "patologias",
                    models.TextField(blank=True, null=True, verbose_name="Patologias"),
                ),
                (
                    "exames_complementares",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exames Complementares"
                    ),
                ),
                (
                    "medicamentos_em_uso",
                    models.TextField(
                        blank=True, null=True, verbose_name="Medicamentos em Uso"
                    ),
                ),
                (
                    "tratamentos_realizados",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tratamentos Anteriores"
                    ),
                ),
                ("objetivo_aluno", models.TextField(verbose_name="Objetivo do Aluno")),
                (
                    "foto_avaliacao_postural",
                    models.ImageField(
                        upload_to="avaliacoes/",
                        verbose_name="Foto da Avalização Postural",
                    ),
                ),
                (
                    "data_reavalicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data para Reavaliação"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avalicoes",
                        to="usuarios.aluno",
                    ),
                ),
            ],
        ),
    ]
