# Generated by Django 5.2.7 on 2025-10-21 04:20

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_colaborador_unidades_old'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, help_text='CPF do usuário. Será usado como identificador único para o login.', max_length=14, null=True, unique=True),
        ),
    ]
