# Generated by Django 5.2.7 on 2025-10-21 04:21

from django.db import migrations

def update_superuser_cpf(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    superuser = Usuario.objects.filter(is_superuser=True).first()
    if superuser and not superuser.cpf:
        superuser.cpf = '36219795814'
        superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_managers_remove_usuario_username_and_more'),
    ]

    operations = [
        migrations.RunPython(update_superuser_cpf),
    ]