# Generated by Django 5.2.7 on 2025-10-21 18:52

import cpf_field.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0012_auto_20251021_0201"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=cpf_field.models.CPFField(
                blank=True,
                help_text="CPF do usuário. Será usado como identificador único.",
                max_length=14,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="endereço de e-mail"
            ),
        ),
    ]
