# Generated by Django 5.2.7 on 2025-11-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColaboradorStudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Colaborador-Studio",
                "verbose_name_plural": "Vínculos Colaborador-Studio",
            },
        ),
        migrations.CreateModel(
            name="FuncaoOperacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_modificacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Studio (Unidade)",
                "verbose_name_plural": "Studios (Unidades)",
                "ordering": ["nome"],
                "permissions": [
                    ("view_dashboard_studio", "Pode visualizar o dashboard do studio"),
                    ("manage_finances_studio", "Pode gerenciar as finanças do studio"),
                    (
                        "manage_collaborators_studio",
                        "Pode gerenciar os colaboradores do studio",
                    ),
                    (
                        "manage_enrollments_studio",
                        "Pode gerenciar matrículas e vendas no studio",
                    ),
                ],
            },
        ),
    ]
