# Generated by Django 5.2.7 on 2025-10-13 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studios", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaboradorstudio",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vinculos_studio",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="colaboradorstudio",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colaboradores_vinculados",
                to="studios.studio",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="colaboradorstudio",
            unique_together={("colaborador", "studio")},
        ),
    ]
