# Generated by Django 5.2.8 on 2025-11-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studio",
            options={
                "ordering": ["nome"],
                "permissions": [
                    ("view_dashboard_studio", "Pode visualizar o dashboard do studio"),
                    ("manage_finances_studio", "Pode gerenciar as finanças do studio"),
                    (
                        "manage_collaborators_studio",
                        "Pode gerenciar os colaboradores do studio",
                    ),
                    (
                        "manage_enrollments_studio",
                        "Pode gerenciar matrículas e vendas no studio",
                    ),
                ],
                "verbose_name": "Studio",
                "verbose_name_plural": "Studios",
            },
        ),
    ]
