# Generated by Django 5.0.6 on 2024-10-19 19:00

from django.db import migrations

def transferir_dados(apps, schema_editor):
    Colaborador = apps.get_model('usuarios', 'Colaborador')
    ColaboradorStudio = apps.get_model('studios', 'ColaboradorStudio')
    
    MAPA_PERMISSAO = {
        'ADMINISTRADOR': 'Admin',
        'RECEPCIONISTA': 'Recep',
        'FISIOTERAPEUTA': 'Fisio',
        'INSTRUTOR': 'Instrutor',
    }

    for colaborador in Colaborador.objects.all():
        perfil_principal = colaborador.perfis.order_by('pk').first()
        permissao_padrao = 'Instrutor'  # Padrão seguro

        if perfil_principal and perfil_principal.nome in MAPA_PERMISSAO:
            permissao_padrao = MAPA_PERMISSAO[perfil_principal.nome]

        # Lendo da relação antiga, agora renomeada para unidades_old
        for studio in colaborador.unidades_old.all():
            ColaboradorStudio.objects.get_or_create(
                colaborador=colaborador,
                studio=studio,
                defaults={'permissao': permissao_padrao}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_initial'),
        # Depende da migração que criou o campo 'unidades' novo
        ('usuarios', '0006_colaborador_unidades'),
    ]

    operations = [
        migrations.RunPython(transferir_dados),
    ]