# Generated by Django 5.2.7 on 2025-10-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0003_migrate_old_unidades_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncaoOperacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
