# Generated by Django 5.0.6 on 2024-10-20 13:00

from django.db import migrations

FUNCOES = ["Admin", "Instrutor", "Fisio", "Recep"]

def criar_funcoes(apps, schema_editor):
    FuncaoOperacional = apps.get_model('studios', 'FuncaoOperacional')
    for nome_funcao in FUNCOES:
        FuncaoOperacional.objects.get_or_create(nome=nome_funcao)

class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_funcaooperacional'),
    ]

    operations = [
        migrations.RunPython(criar_funcoes),
    ]