# Generated by Django 5.2.7 on 2025-10-20 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0005_populate_funcoes_operacionais"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaboradorstudio",
            name="permissao_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="studios.funcaooperacional",
            ),
        ),
    ]
