# Generated by Django 5.0.6 on 2024-10-20 13:15

from django.db import migrations

def transferir_dados_permissao(apps, schema_editor):
    ColaboradorStudio = apps.get_model('studios', 'ColaboradorStudio')
    FuncaoOperacional = apps.get_model('studios', 'FuncaoOperacional')

    # Criar um mapa de nomes para objetos para evitar queries repetidas no loop
    funcoes_map = {funcao.nome: funcao for funcao in FuncaoOperacional.objects.all()}

    for vinculo in ColaboradorStudio.objects.all():
        # Acessa o valor em texto do campo antigo
        nome_permissao = vinculo.permissao
        if nome_permissao in funcoes_map:
            # Associa o objeto FuncaoOperacional correspondente ao novo campo FK
            vinculo.permissao_fk = funcoes_map[nome_permissao]
            vinculo.save(update_fields=['permissao_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_colaboradorstudio_permissao_fk'),
    ]

    operations = [
        migrations.RunPython(transferir_dados_permissao),
    ]