# Generated by Django 5.2.7 on 2025-10-20 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0007_transfer_permissao_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaboradorstudio",
            name="permissao_fk",
        ),
        migrations.AlterField(
            model_name="colaboradorstudio",
            name="permissao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="studios.funcaooperacional",
            ),
        ),
    ]
