# Generated by Django 5.0.6 on 2024-10-20 14:00

from django.db import migrations


def mapear_e_limpar_funcoes(apps, schema_editor):
    """
    Migra as Funcoes Operacionais antigas para o novo padrao,
    reaponta os relacionamentos e remove as funcoes obsoletas.
    """
    FuncaoOperacional = apps.get_model('studios', 'FuncaoOperacional')
    ColaboradorStudio = apps.get_model('studios', 'ColaboradorStudio')

    MAPA_PERMISSOES = {
        'Admin': 'ADMINISTRADOR',
        'Instrutor': 'INSTRUTOR',
        'Fisio': 'FISIOTERAPEUTA',
        'Recep': 'RECEPCIONISTA',
    }
    
    PERMISSOES_FINAIS = [
        'ADMIN_MASTER',
        'ADMINISTRADOR',
        'RECEPCIONISTA',
        'FISIOTERAPEUTA',
        'INSTRUTOR',
    ]

    # 1. Garante que todas as permissões finais existam e as armazena.
    permissoes_finais_objs = {}
    for nome_final in PERMISSOES_FINAIS:
        obj, _ = FuncaoOperacional.objects.get_or_create(nome=nome_final)
        permissoes_finais_objs[nome_final] = obj

    # 2. Mapeia os relacionamentos existentes das permissões antigas para as novas.
    for nome_antigo, nome_novo in MAPA_PERMISSOES.items():
        try:
            permissao_antiga = FuncaoOperacional.objects.get(nome=nome_antigo)
            permissao_nova = permissoes_finais_objs[nome_novo]

            # Se o objeto antigo e o novo forem diferentes, atualiza os vinculos.
            if permissao_antiga.id != permissao_nova.id:
                ColaboradorStudio.objects.filter(permissao=permissao_antiga).update(permissao=permissao_nova)

        except FuncaoOperacional.DoesNotExist:
            # Se a permissão antiga não existe, não há nada a fazer.
            pass

    # 3. Remove todas as permissões que não estão na lista final.
    FuncaoOperacional.objects.exclude(nome__in=PERMISSOES_FINAIS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0008_remove_colaboradorstudio_permissao_fk_and_more'),
        # Adiciona dependência do app de usuarios caso a migração de perfis seja relevante
        ('usuarios', '0004_populate_perfis'), 
    ]

    operations = [
        migrations.RunPython(mapear_e_limpar_funcoes),
    ]
