# Generated by Django 5.2.7 on 2025-10-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_mapear_funcoes_operacionais'),
        ('usuarios', '0007_remove_colaborador_unidades_old'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colaboradorstudio',
            unique_together={('colaborador', 'studio', 'permissao')},
        ),
    ]
