
# Generated by Django 5.0.6 on 2024-10-31

from django.db import migrations, connection

def standardize_funcoes(apps, schema_editor):
    FuncaoOperacional = apps.get_model('studios', 'FuncaoOperacional')
    ColaboradorStudio = apps.get_model('studios', 'ColaboradorStudio')
    
    # 1. Deletar todos os vínculos em ColaboradorStudio para evitar ProtectedError.
    ColaboradorStudio.objects.all().delete()

    # 2. Deletar todas as funções operacionais existentes.
    FuncaoOperacional.objects.all().delete()

    # 3. Resetar o contador de auto-incremento da tabela.
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE studios_funcaooperacional AUTO_INCREMENT = 1;")

    # 4. Criar as novas funções com descrições.
    novas_funcoes = {
        'ADMIN_MASTER': 'Acesso total ao sistema, incluindo todas as unidades.',
        'ADMINISTRADOR': 'Acesso administrativo a uma ou mais unidades.',
        'RECEPCIONISTA': 'Acesso para gerenciar agendamentos, alunos e pagamentos na recepção.',
        'FISIOTERAPEUTA': 'Acesso para realizar avaliações e gerenciar sessões de fisioterapia.',
        'INSTRUTOR': 'Acesso para gerenciar aulas e alunos de Pilates.',
    }
    for nome_funcao, descricao_funcao in novas_funcoes.items():
        FuncaoOperacional.objects.create(nome=nome_funcao, descricao=descricao_funcao)

def revert_standardize_funcoes(apps, schema_editor):
    FuncaoOperacional = apps.get_model('studios', 'FuncaoOperacional')
    ColaboradorStudio = apps.get_model('studios', 'ColaboradorStudio')

    ColaboradorStudio.objects.all().delete()
    
    FuncaoOperacional.objects.filter(nome__in=[
        'ADMIN_MASTER',
        'ADMINISTRADOR',
        'RECEPCIONISTA',
        'FISIOTERAPEUTA',
        'INSTRUTOR',
    ]).delete()
    
    funcoes_originais = {
        "Admin": "Funções administrativas básicas.",
        "Instrutor": "Funções de instrutor de pilates.",
        "Fisio": "Funções de fisioterapeuta.",
        "Recep": "Funções de recepcionista."
    }
    for nome_funcao, desc_funcao in funcoes_originais.items():
        FuncaoOperacional.objects.get_or_create(nome=nome_funcao, defaults={'descricao': desc_funcao})


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0010_alter_colaboradorstudio_unique_together'),
    ]

    operations = [
        migrations.RunPython(standardize_funcoes, reverse_code=revert_standardize_funcoes),
    ]
