# Generated by Django 5.2.7 on 2025-10-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alunos", "0002_alter_aluno_foto"),
        ("studios", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora_inicio", models.DateTimeField()),
                ("duracao_minutos", models.PositiveIntegerField(default=60)),
                ("capacidade_maxima", models.PositiveIntegerField(default=3)),
                (
                    "tipo_aula",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("EXPERIMENTAL", "Experimental"),
                            ("REPOSICAO", "Reposição"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                (
                    "instrutor_principal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aulas_principais",
                        to="usuarios.colaborador",
                    ),
                ),
                (
                    "instrutor_substituto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aulas_substitutas",
                        to="usuarios.colaborador",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="studios.studio",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aulas",
                        to="agendamentos.modalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["data_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AulaAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_presenca",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE_COM_REPO", "Ausente com Reposição"),
                            ("AUSENTE_SEM_REPO", "Ausente sem Reposição"),
                            ("AGENDADO", "Agendado"),
                        ],
                        default="AGENDADO",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas_agendadas",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alunos_inscritos",
                        to="agendamentos.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento de Aluno",
                "verbose_name_plural": "Agendamentos de Alunos",
                "unique_together": {("aula", "aluno")},
            },
        ),
        migrations.CreateModel(
            name="Reposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_expiracao", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("UTILIZADA", "Utilizada"),
                            ("EXPIRADA", "Expirada"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "agendamento_origem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reposicao_gerada",
                        to="agendamentos.aulaaluno",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reposicoes",
                        to="alunos.aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloqueioAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=255)),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueios",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueio de Agenda",
                "verbose_name_plural": "Bloqueios de Agenda",
                "unique_together": {("studio", "data")},
            },
        ),
        migrations.CreateModel(
            name="HorarioTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_trabalho",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de Trabalho",
                "verbose_name_plural": "Horários de Trabalho",
                "unique_together": {("studio", "dia_semana")},
            },
        ),
        migrations.CreateModel(
            name="ListaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("NOTIFICADO", "Notificado"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_espera",
                        to="alunos.aluno",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_espera",
                        to="agendamentos.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Espera",
                "verbose_name_plural": "Listas de Espera",
                "ordering": ["data_inscricao"],
                "unique_together": {("aula", "aluno")},
            },
        ),
    ]
