# Generated by Django 5.2.7 on 2025-10-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora_inicio", models.DateTimeField()),
                ("duracao_minutos", models.PositiveIntegerField(default=60)),
                ("capacidade_maxima", models.PositiveIntegerField(default=3)),
                (
                    "tipo_aula",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("EXPERIMENTAL", "Experimental"),
                            ("REPOSICAO", "Reposição"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["data_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AulaAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_presenca",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE_COM_REPO", "Ausente com Reposição"),
                            ("AUSENTE_SEM_REPO", "Ausente sem Reposição"),
                            ("AGENDADO", "Agendado"),
                        ],
                        default="AGENDADO",
                        max_length=20,
                    ),
                ),
            ],
            options={
<<<<<<< HEAD
                "verbose_name": "Lista de Espera",
                "verbose_name_plural": "Listas de Espera",
                "ordering": ["data_inscricao"],
            },
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
=======
                "verbose_name": "Agendamento de Aluno",
                "verbose_name_plural": "Agendamentos de Alunos",
            },
>>>>>>> db5a7261e5b4ab7db8fc96ca5106849fe1b669cb
        ),
        migrations.CreateModel(
            name="BloqueioAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Bloqueio de Agenda",
                "verbose_name_plural": "Bloqueios de Agenda",
            },
        ),
        migrations.CreateModel(
            name="CreditoAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_expiracao", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("UTILIZADA", "Utilizada"),
                            ("EXPIRADA", "Expirada"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HorarioTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
            ],
            options={
                "verbose_name": "Horário de Trabalho",
                "verbose_name_plural": "Horários de Trabalho",
            },
        ),
        migrations.CreateModel(
            name="ListaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("NOTIFICADO", "Notificado"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de Espera",
                "verbose_name_plural": "Listas de Espera",
                "ordering": ["data_inscricao"],
            },
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_expiracao", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("UTILIZADA", "Utilizada"),
                            ("EXPIRADA", "Expirada"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
