# Generated by Django 5.2.7 on 2025-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora_inicio", models.DateTimeField()),
                ("duracao_minutos", models.IntegerField(default=60)),
                ("capacidade_maxima", models.PositiveIntegerField()),
                (
                    "tipo_aula",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("EXPERIMENTAL", "Experimental"),
                            ("REPOSICAO", "Reposição"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "aulas",
            },
        ),
        migrations.CreateModel(
            name="AulaAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_presenca",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE_COM_REPO", "Ausente com Reposição"),
                            ("AUSENTE_SEM_REPO", "Ausente sem Reposição"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "aulas_alunos",
            },
        ),
        migrations.CreateModel(
            name="ListaEspera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando"),
                            ("NOTIFICADO", "Notificado"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "lista_espera",
                "ordering": ["data_inscricao"],
            },
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "modalidades",
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("NAO_LIDA", "Não Lida"), ("LIDA", "Lida")],
                        default="NAO_LIDA",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notificacoes",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Reposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_expiracao", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("UTILIZADA", "Utilizada"),
                            ("EXPIRADA", "Expirada"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "reposicoes",
            },
        ),
    ]
