# Generated by Django 5.2.7 on 2025-10-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("alunos", "0002_alter_aluno_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditoAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_expiracao", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("UTILIZADA", "Utilizada"),
                            ("EXPIRADA", "Expirada"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "agendamento_origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credito_aula_gerado",
                        to="agendamentos.aulaaluno",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditos_aula",
                        to="alunos.aluno",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aulaaluno",
            name="credito_utilizado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamento_uso",
                to="agendamentos.creditoaula",
            ),
        ),
    ]
