# Generated by Django 5.2.7 on 2025-10-14 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("alunos", "0001_initial"),
        ("studios", "0002_initial"),
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="instrutor_principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aulas_principais",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="instrutor_substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aulas_substitutas",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studios.studio"
            ),
        ),
        migrations.AddField(
            model_name="aulaaluno",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="alunos.aluno"
            ),
        ),
        migrations.AddField(
            model_name="aulaaluno",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agendamentos.aula"
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="alunos",
            field=models.ManyToManyField(
                through="agendamentos.AulaAluno", to="alunos.aluno"
            ),
        ),
        migrations.AddField(
            model_name="listaespera",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lista_espera",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="listaespera",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lista_espera",
                to="agendamentos.aula",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="agendamentos.modalidade",
            ),
        ),
        migrations.AddField(
            model_name="notificacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reposicao",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposicoes",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="reposicao",
            name="aula_origem",
            field=models.ForeignKey(
                help_text="Aula que gerou o crédito de reposição.",
                on_delete=django.db.models.deletion.CASCADE,
                to="agendamentos.aula",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aulaaluno",
            unique_together={("aula", "aluno")},
        ),
    ]
