# Generated by Django 5.2.7 on 2025-10-30 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("alunos", "0001_initial"),
        ("studios", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="instrutor_principal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aulas_principais",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="instrutor_substituto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aulas_substitutas",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas",
                to="studios.studio",
            ),
        ),
        migrations.AddField(
            model_name="aulaaluno",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas_agendadas",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="aulaaluno",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos_inscritos",
                to="agendamentos.aula",
            ),
        ),
        migrations.AddField(
            model_name="bloqueioagenda",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueios",
                to="studios.studio",
            ),
        ),
        migrations.AddField(
            model_name="creditoaula",
            name="agendamento_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credito_aula_gerado",
                to="agendamentos.aulaaluno",
            ),
        ),
        migrations.AddField(
            model_name="creditoaula",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditos_aula",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="aulaaluno",
            name="credito_utilizado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamento_uso",
                to="agendamentos.creditoaula",
            ),
        ),
        migrations.AddField(
            model_name="horariotrabalho",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios_trabalho",
                to="studios.studio",
            ),
        ),
        migrations.AddField(
            model_name="listaespera",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lista_espera",
                to="alunos.aluno",
            ),
        ),
        migrations.AddField(
            model_name="listaespera",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lista_espera",
                to="agendamentos.aula",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aulas",
                to="agendamentos.modalidade",
            ),
        ),
        migrations.AddField(
            model_name="reposicao",
            name="agendamento_origem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposicao_gerada",
                to="agendamentos.aulaaluno",
            ),
        ),
        migrations.AddField(
            model_name="reposicao",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposicoes",
                to="alunos.aluno",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bloqueioagenda",
            unique_together={("studio", "data")},
        ),
        migrations.AlterUniqueTogether(
            name="aulaaluno",
            unique_together={("aula", "aluno")},
        ),
        migrations.AlterUniqueTogether(
            name="horariotrabalho",
            unique_together={("studio", "dia_semana")},
        ),
        migrations.AlterUniqueTogether(
            name="listaespera",
            unique_together={("aula", "aluno")},
        ),
    ]
