# Generated by Django 5.2.7 on 2025-11-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0002_initial"),
        ("financeiro", "0002_alter_matricula_options_alter_pagamento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditoaula",
            name="matricula_origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creditos_gerados",
                to="financeiro.matricula",
            ),
        ),
    ]
