# Generated by Django 5.2.7 on 2025-10-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0002_initial"),
        ("alunos", "0003_remove_aluno_cpf_alter_aluno_contato_and_more"),
        ("studios", "0003_migrate_old_unidades_data"),
        ("usuarios", "0007_remove_colaborador_unidades_old"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aula",
            options={
                "ordering": ["data_hora_inicio"],
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
            },
        ),
        migrations.AlterModelOptions(
            name="aulaaluno",
            options={
                "verbose_name": "Agendamento de Aluno",
                "verbose_name_plural": "Agendamentos de Alunos",
            },
        ),
        migrations.AlterModelOptions(
            name="listaespera",
            options={
                "ordering": ["data_inscricao"],
                "verbose_name": "Lista de Espera",
                "verbose_name_plural": "Listas de Espera",
            },
        ),
        migrations.RemoveField(
            model_name="aula",
            name="alunos",
        ),
        migrations.RemoveField(
            model_name="reposicao",
            name="aula_origem",
        ),
        migrations.AddField(
            model_name="reposicao",
            name="agendamento_origem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposicao_gerada",
                to="agendamentos.aulaaluno",
            ),
        ),
        migrations.AlterField(
            model_name="aula",
            name="capacidade_maxima",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="aula",
            name="duracao_minutos",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="aula",
            name="instrutor_principal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aulas_principais",
                to="usuarios.colaborador",
            ),
        ),
        migrations.AlterField(
            model_name="aula",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aulas",
                to="agendamentos.modalidade",
            ),
        ),
        migrations.AlterField(
            model_name="aula",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas",
                to="studios.studio",
            ),
        ),
        migrations.AlterField(
            model_name="aulaaluno",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas_agendadas",
                to="alunos.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="aulaaluno",
            name="aula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos_inscritos",
                to="agendamentos.aula",
            ),
        ),
        migrations.AlterField(
            model_name="aulaaluno",
            name="status_presenca",
            field=models.CharField(
                choices=[
                    ("PRESENTE", "Presente"),
                    ("AUSENTE_COM_REPO", "Ausente com Reposição"),
                    ("AUSENTE_SEM_REPO", "Ausente sem Reposição"),
                    ("AGENDADO", "Agendado"),
                ],
                default="AGENDADO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="modalidade",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="listaespera",
            unique_together={("aula", "aluno")},
        ),
        migrations.AlterModelTable(
            name="aula",
            table=None,
        ),
        migrations.AlterModelTable(
            name="aulaaluno",
            table=None,
        ),
        migrations.AlterModelTable(
            name="listaespera",
            table=None,
        ),
        migrations.AlterModelTable(
            name="modalidade",
            table=None,
        ),
        migrations.AlterModelTable(
            name="reposicao",
            table=None,
        ),
        migrations.CreateModel(
            name="BloqueioAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=255)),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueios",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueio de Agenda",
                "verbose_name_plural": "Bloqueios de Agenda",
                "unique_together": {("studio", "data")},
            },
        ),
        migrations.CreateModel(
            name="HorarioTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_trabalho",
                        to="studios.studio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de Trabalho",
                "verbose_name_plural": "Horários de Trabalho",
                "unique_together": {("studio", "dia_semana")},
            },
        ),
        migrations.DeleteModel(
            name="Notificacao",
        ),
    ]
